name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/android-ci:latest

  android-tests:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/android-ci:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Start Emulator
        run: |
          echo "Starting emulator"
          export DISPLAY=:1
          nohup emulator -avd test_avd -no-window -no-audio -no-boot-anim -accel auto -no-snapshot &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock screen
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0
          adb shell settings put secure sysui_demo_allowed 1
          adb shell am broadcast -a com.android.systemui.demo -e command enter
          echo "Waiting for emulator to boot..."
          while [[ $(adb shell getprop sys.boot_completed) != 1 ]]; do
            sleep 5
            echo "Waiting..."
          done
          echo "Emulator booted!"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Run UI Tests
        run: ./gradlew connectedCheck